#MATH 1350 - Lab 2
# Shahin Yousefi A00930414

library(mosaic)
setwd("D:/CIT/Level 02/MATH-1350/week01&02/lab/")
examscores <- read.delim("data/Lab2.txt")
with(examscores,stem(Score))
histogram(~Score, data=examscores, main="Exam Score Distribution", xlab = "Score(out of 80)", ylab = "Frequency", type = "c", col="#880088", breaks=seq(30,80,5), width=20,) 
examscores$Set=as.factor(examscores$Set)
mean(~Score, data = examscores)
median(~Score, data = examscores)
sd(~Score, data = examscores)
var(~Score, data = examscores)
max(~Score, data = examscores)- min(~Score, data = examscores)
IQR(~Score, data = examscores)
favstats(~Score, data = examscores)
with(examscores, quantile(Score, 0.8))
mean(Score~Set,data = examscores)
median(Score~Set, data = examscores)
sd(Score~Set, data = examscores)
var(Score~Set, data = examscores)
max(Score~Set, data = examscores)- min(Score~Set, data = examscores)
IQR(Score~Set, data = examscores)
histogram(~Score|Set,data = examscores, main="Exam Score Distribution", xlab = "Score(out of 80)", ylab = "Frequency", type = "p", col="#880088", breaks=seq(30,80,5), width=20,layout = c(1,2))
